<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/06/27 20:00:49

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=acres100',
  'username' => 'root',
  'password' => 'dynamite',
  'name' => 'doctrine',
)),);
