<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/06/25 12:31:39

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=mysite',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
