<?php
// auto-generated by sfViewConfigHandler
// date: 2015/07/05 23:55:28
$response = $this->context->getResponse();

if ($this->actionName.$this->viewName == 'indexSuccess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}

if ($templateName.$this->viewName == 'indexSuccess')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', '100 acres', false, false);
  $response->addMeta('description', 'Search Delhi/NCR real estate, Delhi/NCR property, property in Delhi/NCR, real estate in Delhi/NCR. Buy / Rent residential apartments, flats, house, bungalow, villa in Delhi/NCR. Search property for sale, rent and PG Delhi/NCR Now! Get best property deals from Delhi/NCR real estate agents, brokers, dealers and real property owners', false, false);
  $response->addMeta('keywords', '100 acres, team9', false, false);
  $response->addMeta('language', 'en', false, false);
  $response->addMeta('robots', 'index, follow', false, false);

  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('home.css', '', array ());
  $response->addJavascript('jquery_min.js', '', array ());
  $response->addJavascript('home.js', '', array ());
  $response->addJavascript('register.js', '', array ());
  $response->addJavascript('email.js', '', array ());
  $response->addJavascript('autosuggest.js', '', array ());
  $response->addJavascript('jquery.js', '', array ());
  $response->addJavascript('jquery_ui.js', '', array ());
}
else
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('home.css', '', array ());
  $response->addJavascript('jquery_min.js', '', array ());
  $response->addJavascript('home.js', '', array ());
  $response->addJavascript('register.js', '', array ());
  $response->addJavascript('email.js', '', array ());
}

