<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/07/01 14:38:07

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=symfonydb',
  'username' => 'root',
  'password' => 'jyotidgr8',
  'name' => 'doctrine',
)),);
