<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/07/05 12:19:47

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=acres100',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
