<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2015/07/05 12:21:06
sfConfig::add(array(
  'mod_login_enabled' => true,
  'mod_login_view_class' => 'sfPHP',
  'mod_login_index_enable_login' => 'off',
));
