<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2015/07/05 12:21:06
sfConfig::add(array(
  'mod_form_enabled' => true,
  'mod_form_view_class' => 'sfPHP',
  'mod_form_index_enable_login' => 'on',
));
